name: hello-world-gtk
version: '0.1'
summary: Gtk Hello World example
description: A simple Gtk example
base: core22
confinement: strict

apps:
  hello-world-gtk:
    command: src/hello-world-gtk
    plugs:
      - x11
      - wayland

parts:
  hello-world-gtk:
    plugin: dump
    source: .
    stage-packages:
      - libgtk-4-1
